import { useMemo, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useSimulation } from "../simulation/SimulationContext";

export function SecondaryTools() {
  const { metrics, interventions, setBusinessMode, businessMode } =
    useSimulation();
  const [open, setOpen] = useState<"email" | "report" | null>(null);

  const emailDraft = useMemo(() => {
    const subject = "NutriPlan.AI — Food access simulation summary";
    const body = `Mayor's office — prioritized briefing\n\nEquity Impact Score: ${metrics.equityScore}/100\nPopulation positively impacted: ${interventions.length ? metrics.populationImpacted.toLocaleString() : "—"}\nModeled travel-time reduction: ${interventions.length ? `${metrics.travelTimeReductionPct.toFixed(1)}%` : "—"}\nEstimated public health savings: ${interventions.length ? `$${(metrics.healthcareSavingsUsd / 1e6).toFixed(2)}M` : "—"}\n\nKey insight:\n${metrics.insight}\n\n— Generated by NutriPlan.AI (simulation preview)`;
    return { subject, body };
  }, [metrics, interventions.length]);

  return (
    <div className="pointer-events-auto absolute left-6 top-28 z-30 flex max-w-xs flex-col gap-3">
      <div className="glass-panel flex flex-col gap-2 p-3">
        <ToolRow
          label="Generate Mayor Email"
          icon="✉️"
          onClick={() => setOpen((v) => (v === "email" ? null : "email"))}
          active={open === "email"}
        />
        <ToolRow
          label="Generate City Report"
          icon="📄"
          onClick={() => setOpen((v) => (v === "report" ? null : "report"))}
          active={open === "report"}
        />
        <button
          type="button"
          onClick={() => setBusinessMode(!businessMode)}
          className={`flex w-full items-center justify-between rounded-xl px-3 py-2.5 text-left text-sm transition ${
            businessMode
              ? "bg-amber-500/15 text-amber-200 ring-1 ring-amber-400/30"
              : "text-white/70 hover:bg-white/[0.06]"
          }`}
        >
          <span className="flex items-center gap-2">
            <span>🏪</span> Business opportunity mode
          </span>
          <span className="text-[10px] uppercase tracking-wider text-white/40">
            {businessMode ? "On" : "Off"}
          </span>
        </button>
      </div>

      <AnimatePresence>
        {open === "email" && (
          <motion.div
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 6 }}
            className="glass-panel max-h-64 overflow-auto p-4 text-xs leading-relaxed text-white/80"
          >
            <div className="mb-2 text-[10px] font-semibold uppercase tracking-[0.2em] text-white/40">
              Draft preview
            </div>
            <div className="font-medium text-neon">Subject: {emailDraft.subject}</div>
            <pre className="mt-3 whitespace-pre-wrap font-sans text-[11px] text-white/70">
              {emailDraft.body}
            </pre>
          </motion.div>
        )}
        {open === "report" && (
          <motion.div
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 6 }}
            className="glass-panel max-h-72 overflow-auto p-4 text-xs"
          >
            <div className="mb-3 border-b border-white/10 pb-2 text-center">
              <div className="text-[10px] uppercase tracking-[0.3em] text-white/40">
                City planning office
              </div>
              <div className="mt-1 text-sm font-bold text-white">
                Food access intervention brief
              </div>
            </div>
            <Section title="Executive summary" />
            <p className="text-[11px] leading-relaxed text-white/70">
              Modeled outcomes reflect predictive GIS + health risk layers under
              NutriPlan.AI scenario assumptions. Not a commitment of funding.
            </p>
            <Section title="Simulation metrics" />
            <ul className="list-inside list-disc space-y-1 text-[11px] text-white/70">
              <li>Equity Impact Score: {metrics.equityScore}/100</li>
              <li>
                Population impacted:{" "}
                {interventions.length
                  ? metrics.populationImpacted.toLocaleString()
                  : "Pending placement"}
              </li>
              <li>
                Travel burden reduction:{" "}
                {interventions.length
                  ? `${metrics.travelTimeReductionPct.toFixed(1)}%`
                  : "—"}
              </li>
            </ul>
            <Section title="Policy notes" />
            <p className="text-[11px] leading-relaxed text-white/70">
              {metrics.insight}
            </p>
            <div className="mt-4 text-[10px] text-white/35">
              NutriPlan.AI — preview document (frontend demo)
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

function ToolRow({
  label,
  icon,
  onClick,
  active,
}: {
  label: string;
  icon: string;
  onClick: () => void;
  active: boolean;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`flex w-full items-center justify-between rounded-xl px-3 py-2.5 text-left text-sm transition ${
        active ? "bg-white/[0.1] text-white" : "text-white/70 hover:bg-white/[0.06]"
      }`}
    >
      <span className="flex items-center gap-2">
        <span>{icon}</span> {label}
      </span>
      <span className="text-white/35">{active ? "▾" : "▸"}</span>
    </button>
  );
}

function Section({ title }: { title: string }) {
  return (
    <div className="mb-1 mt-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-cyanGlow/90">
      {title}
    </div>
  );
}
